#!/bin/bash

source config

config() {
  cam_version=${version:-v3}
	cam_width=${width:-1280}
	cam_height=${height:-1024}
	cam_hflip=${hflip:-1}
	cam_vflip=${vflip:-1}
	save_path=${path:-$PWD/photos}
	img_name=${name:-"temp.jpg"}
	persistence=${persistence:-true}
	tg_forwarding=${tgforwarding:-false}
}

main() {
	local now save_path persistence tg_forwarding cam_version
	config


  if [ ! -d "${save_path}" ]; then
      mkdir -p "${save_path}"
  fi

#todo: check if version is valid
if [ "${cam_version}" = "v3" ]; then
	##CameraV3
	/usr/bin/libcamera-jpeg --width "${cam_width}" --height "${cam_height}" --hflip "${cam_hflip}" --vflip "${cam_vflip}" -n --hdr -o "${save_path}"/"${img_name}"

elif [ "${cam_version}" = "v2_nvnoir" ]; then
  ##CameraV2 - Night vision NoIR
  /usr/bin/libcamera-still --width "${cam_width}" --height "${cam_height}" --hflip "${cam_hflip}" --vflip "${cam_vflip}" --ev 0 -o "${save_path}"/"${img_name}"
  #todo: implement commands for all other versions
fi




if [ $? = 0 ]; then

  if [ "${persistence}" = true ]; then
    persist
  fi

	if [ "${tg_forwarding}" = true ]; then
	./transmitPhoto "${save_path}/${img_name}"
  fi

else
  echo "smth went wrong"
  #todo: implement retry handling, show error to user
fi

}

persist()
{
  local file
  now=$(date +"%Y-%m-%d_%H:%M:%S")

  file="${save_path}/${now}.jpg"
  /bin/cp "${save_path}/${img_name}" "${file}"

  echo "Image persisted at ${file}"
}

main "$@"
