#!/bin/bash

source config

config() {
	cam_width=${width:-1280}
	cam_height=${height:-1024}
	cam_hflip=${hflip:-1}
	cam_vflip=${vflip:-1}
	save_path=${path:-$PWD/photos}
	img_name=${name:-"temp.jpg"}
	persistence=${persistence:-true}
}

main() {
	local now save_path persistence
	config


  if [ ! -d "${save_path}" ]; then
      mkdir -p "${save_path}"
  fi

	##CameraV3
	/usr/bin/libcamera-jpeg --width ${cam_width} --height ${cam_height} --hflip ${cam_hflip} --vflip ${cam_vflip} -n --hdr -o "${save_path}/${img_file}"
	./transmitPhoto "${save_path}/${img_file}"


if [ $? = 0 ]; then

  if [ "${persistence}" = true ]; then
    persist
  fi

else
  echo "smth went wrong"
  #todo: implement retry handling, show error to user
fi

}

persist()
{
  local file
  now=$(date +"%Y-%m-%d_%H:%M:%S")

  file="${save_path}/${now}.jpg"
  /bin/mv "${save_path}/${img_name}" "${file}"

  echo "Image persisted at ${file}"
}

main "$@"
