#!/bin/bash

source ../config

config() {
  cam_type=${type:-rpicam}
	cam_width=${width:-1280}
	cam_height=${height:-1024}
	cam_hflip=${hflip:-1}
	cam_vflip=${vflip:-1}
	save_path=${path:-$PWD/photos}
	img_name=${name:-"temp.jpg"}
	persistence=${persistence:-true}
	tg_forwarding=${tgforwarding:-false}
}

main() {
	local now save_path persistence tg_forwarding cam_type
	config

  if [ ! -d "${save_path}" ]; then
      mkdir -p "${save_path}"
  fi

#use version from argument, else use from config
  if [ $# -eq 1 ]
    then
      cam_type=$1
  fi

#todo: check if version is valid
if [ "${cam_type}" = "rpicam" ]; then
	##rpicam
	/usr/bin/libcamera-jpeg --width "${cam_width}" --height "${cam_height}" --hflip "${cam_hflip}" --vflip "${cam_vflip}" -n --hdr -o "${save_path}"/"${img_name}"

  #todo: check if camera v2 and v3 can be executed with the same command

elif [ "${cam_type}" = "webcam" ]; then
  ##webcam
  /usr/bin/fswebcam -r "${cam_width}"x"${cam_height}" "${save_path}"/"${img_name}"
  #todo: implement commands for all other versions
fi


if [ $? = 0 ]; then

  if [ "${persistence}" = true ]; then
    persist
  fi

	if [ "${tg_forwarding}" = true ]; then
	./transmitPhoto "${save_path}/${img_name}"
  fi

else
  echo "smth went wrong"
  #todo: implement retry handling, show error to user
fi

}

persist()
{
  local file
  now=$(date +"%Y-%m-%d_%H:%M:%S")

  file="${save_path}/${now}.jpg"
  /bin/cp "${save_path}/${img_name}" "${file}"

  echo "Image persisted at ${file}"
}

main "$@"
