#!/bin/bash

source config

config() {
  bot_token=${bot_token}
	receiver=${receiver}
}

#todo: implement checks
main() {
	local bot_token receiver
	config

url="https://api.telegram.org/bot${bot_token}/sendPhoto"

curl -X POST -H "Content-Type: multipart/form-data" -F "chat_id=${receiver}" -F "photo=@$1" "$url"
}